# Model definition for the baseline Conditional2DUnet normals pipeline.
model:
  unet:
    name: UNet2DConditionModel
    kwargs:
      sample_size: 128
      in_channels: 6
      out_channels: 3
      down_block_types:
      - CrossAttnDownBlock2D
      - CrossAttnDownBlock2D
      - DownBlock2D
      up_block_types:
      - UpBlock2D
      - CrossAttnUpBlock2D
      - CrossAttnUpBlock2D
      block_out_channels:
      - 128
      - 192
      - 256
      layers_per_block: 1
      attention_head_dim:
      - 4
      - 4
      - 8
      cross_attention_dim: 384
      norm_num_groups: 32
      resnet_time_scale_shift: scale_shift
      use_linear_projection: true
  scheduler:
    name: DDPMScheduler
    kwargs:
      num_train_timesteps: 1000
      beta_schedule: squaredcos_cap_v2
      prediction_type: epsilon
      clip_sample: false
      timestep_spacing: leading

