base_config:
- config/logging.yaml
- config/wandb.yaml
- config/dataset_normals/dataset_train.yaml
- config/dataset_normals/dataset_val.yaml
- config/dataset_normals/dataset_vis.yaml
- config/model_baseline.yaml

pipeline:
  name: BaselineNormalsPipeline
  kwargs:
    default_denoising_steps: 60
    default_processing_resolution: 256

augmentation:
  color_jitter_p: 0.3
  gaussian_blur_p: 0.3
  motion_blur_p: 0.3
  gaussian_blur_sigma: 4
  motion_blur_kernel_size: 11
  motion_blur_angle_range: 360
  jitter_brightness_factor: 0.5
  jitter_contrast_factor: 0.5
  jitter_saturation_factor: 0.5
  jitter_hue_factor: 0.2

dataloader:
  num_workers: 2
  effective_batch_size: 4
  max_train_batch_size: 1
  seed: 2024
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4

trainer:
  name: BaselineNormalsTrainer
  init_seed: 2024
  save_period: 100
  backup_period: 2000
  validation_period: 500
  visualization_period: 1000

multi_res_noise:
  strength: 0.4
  annealed: true
  downscale_strategy: original

gt_normals_type: normals
gt_mask_type: null

max_epoch: 10000
max_iter: 40000

loss:
  name: mse_loss
  kwargs:
    reduction: mean

lr: 3.0e-05
lr_scheduler:
  name: IterExponential
  kwargs:
    total_iter: 35000
    final_ratio: 0.1
    warmup_steps: 500

validation:
  denoising_steps: 60
  ensemble_size: 1
  processing_res: 320
  match_input_res: true
  resample_method: bilinear
  main_val_metric: mean_angular_error
  main_val_metric_goal: minimize
  init_seed: 0

eval:
  align_max_res: null
  eval_metrics:
  - mean_angular_error
  - sub11_25_error

